# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Yukishiro
#
# Reproducible build for the experimental Meltype responsibility-split Mozc IME.
param(
    [string]$MozcSource = (Join-Path $env:USERPROFILE 'mozc'),
    [string]$Python = 'python',
    [string]$Bazelisk = 'bazelisk',
    [string]$VcPath = '',
    [string]$DiskCache = '',
    [switch]$SkipTipBuild,
    [switch]$SkipTests
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Invoke-Native([string]$FilePath, [string[]]$Arguments, [string]$Failure) {
    $previous = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try { & $FilePath @Arguments 2>&1 | ForEach-Object { Write-Host $_ } }
    finally { $ErrorActionPreference = $previous }
    if ($LASTEXITCODE -ne 0) { throw "$Failure (exit=$LASTEXITCODE)" }
}

function Replace-Once([string]$Path, [string]$Needle, [string]$Replacement, [string]$AlreadyPresent) {
    $content = Get-Content -Raw -LiteralPath $Path
    if ($AlreadyPresent -and $content.Contains($AlreadyPresent)) { return }
    if (-not $content.Contains($Needle)) {
        throw ('Patch anchor not found: ' + $Path + [Environment]::NewLine + $Needle)
    }
    $content = $content.Replace($Needle, $Replacement)
    Set-Content -LiteralPath $Path -Value $content -Encoding utf8NoBOM
}

function Read-DictionaryWords([string]$Path) {
    $words = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
    foreach ($line in Get-Content -LiteralPath $Path -Encoding utf8) {
        $clean = ($line -replace '#.*$', '').Trim()
        if (-not $clean) { continue }
        foreach ($word in ($clean -split '\s+')) {
            if ($word) { [void]$words.Add($word.ToLowerInvariant()) }
        }
    }
    return $words
}

function Write-CppArray([System.Text.StringBuilder]$Builder, [string]$Name, $Words) {
    $items = @($Words | Sort-Object -Unique)
    [void]$Builder.AppendLine("inline constexpr std::array<std::string_view, $($items.Count)> $Name = {")
    foreach ($word in $items) {
        $escaped = $word.Replace('\', '\\').Replace('"', '\"')
        [void]$Builder.AppendLine(('    "' + $escaped + '",'))
    }
    [void]$Builder.AppendLine('};')
    [void]$Builder.AppendLine()
}

function Write-GeneratedLexicon([string]$RepoRoot, [string]$Destination) {
    $english = Read-DictionaryWords (Join-Path $RepoRoot 'dictionaries\english.txt')
    $readable = Read-DictionaryWords (Join-Path $RepoRoot 'dictionaries\english-readable.txt')
    $proper = Read-DictionaryWords (Join-Path $RepoRoot 'dictionaries\propernouns.txt')
    $japanese = Read-DictionaryWords (Join-Path $RepoRoot 'dictionaries\japanese.txt')

    foreach ($seed in @(
        'the', 'then', 'node', 'network', 'commit', 'issue', 'github',
        'reflect', 'invite', 'linux', 'kernel', 'build', 'server', 'cache',
        'debug', 'deploy'
    )) {
        [void]$english.Add($seed)
    }

    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('// Generated by Build-ResponsibilityIme.ps1. Do not edit.')
    [void]$sb.AppendLine('#ifndef MOZC_WIN32_TIP_MELTYPE_GENERATED_LEXICON_H_')
    [void]$sb.AppendLine('#define MOZC_WIN32_TIP_MELTYPE_GENERATED_LEXICON_H_')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('#include <array>')
    [void]$sb.AppendLine('#include <string_view>')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('namespace mozc::win32::tsf::meltype {')
    [void]$sb.AppendLine()
    Write-CppArray $sb 'kEnglishWords' $english
    Write-CppArray $sb 'kReadableEnglishWords' $readable
    Write-CppArray $sb 'kProperNouns' $proper
    Write-CppArray $sb 'kJapaneseWords' $japanese
    [void]$sb.AppendLine('}  // namespace mozc::win32::tsf::meltype')
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('#endif  // MOZC_WIN32_TIP_MELTYPE_GENERATED_LEXICON_H_')
    Set-Content -LiteralPath $Destination -Value $sb.ToString() -Encoding utf8NoBOM
}

$experimental = $PSScriptRoot
$nativeMozc = Split-Path -Parent $experimental
$repoRoot = (Resolve-Path (Join-Path $experimental '..\..\..')).Path
$commit = (Get-Content -Raw -LiteralPath (Join-Path $nativeMozc 'MOZC_COMMIT')).Trim()

if (-not (Test-Path (Join-Path $MozcSource '.git'))) {
    New-Item -ItemType Directory -Force -Path $MozcSource | Out-Null
    Invoke-Native git @('-C', $MozcSource, 'init', '-q') 'git init failed'
    Invoke-Native git @('-C', $MozcSource, 'remote', 'add', 'origin', 'https://github.com/google/mozc.git') 'git remote failed'
    Invoke-Native git @('-C', $MozcSource, 'fetch', '-q', '--depth', '1', 'origin', $commit) "failed to fetch Mozc $commit"
    Invoke-Native git @('-C', $MozcSource, 'checkout', '-q', 'FETCH_HEAD') 'git checkout failed'
    Invoke-Native git @('-C', $MozcSource, 'submodule', 'update', '-q', '--init', '--recursive', '--depth', '1') 'submodule update failed'
} else {
    $head = (& git -C $MozcSource rev-parse HEAD).Trim()
    if ($head -ne $commit) {
        Invoke-Native git @('-C', $MozcSource, 'fetch', '-q', '--depth', '1', 'origin', $commit) "failed to fetch Mozc $commit"
        Invoke-Native git @('-C', $MozcSource, 'checkout', '-q', '--detach', $commit) 'failed to checkout pinned Mozc commit'
    }
}

$src = Join-Path $MozcSource 'src'
$target = Join-Path $src 'win32\tip\meltype'
New-Item -ItemType Directory -Force -Path $target | Out-Null
foreach ($name in @(
    'responsibility_decoder.h',
    'responsibility_decoder.cc',
    'responsibility_runtime.h',
    'responsibility_runtime.cc',
    'responsibility_decoder_test.cc',
    'responsibility_runtime_test.cc',
    'boundary_mozc_bridge.cc',
    'BUILD.bazel'
)) {
    Copy-Item -LiteralPath (Join-Path $experimental ('src\' + $name)) -Destination $target -Force
}
Write-GeneratedLexicon -RepoRoot $repoRoot -Destination (Join-Path $target 'generated_lexicon.h')

$privateHeader = Join-Path $src 'win32\tip\tip_private_context.h'
$needle = @'
  const commands::Output& last_output() const;
  commands::Output* mutable_last_output();
'@
$replacement = @'
  const commands::Output& last_output() const;
  commands::Output* mutable_last_output();

  // Experimental Meltype responsibility split: preserve the original Mozc
  // output before the TSF layer applies literal/Japanese ownership.
  const commands::Output& responsibility_base_output() const;
  commands::Output* mutable_responsibility_base_output();
'@
Replace-Once -Path $privateHeader -Needle $needle -Replacement $replacement -AlreadyPresent 'responsibility_base_output() const'

$privateImpl = Join-Path $src 'win32\tip\tip_private_context.cc'
$needle = @'
  commands::Output last_output_;
  VirtualKey last_down_key_;
'@
$replacement = @'
  commands::Output last_output_;
  commands::Output responsibility_base_output_;
  VirtualKey last_down_key_;
'@
Replace-Once -Path $privateImpl -Needle $needle -Replacement $replacement -AlreadyPresent 'commands::Output responsibility_base_output_;'

$needle = @'
Output* TipPrivateContext::mutable_last_output() {
  return &state_->last_output_;
}

const VirtualKey& TipPrivateContext::last_down_key() const {
'@
$replacement = @'
Output* TipPrivateContext::mutable_last_output() {
  return &state_->last_output_;
}

const Output& TipPrivateContext::responsibility_base_output() const {
  return state_->responsibility_base_output_;
}

Output* TipPrivateContext::mutable_responsibility_base_output() {
  return &state_->responsibility_base_output_;
}

const VirtualKey& TipPrivateContext::last_down_key() const {
'@
Replace-Once -Path $privateImpl -Needle $needle -Replacement $replacement -AlreadyPresent 'TipPrivateContext::responsibility_base_output() const'

$keyHandler = Join-Path $src 'win32\tip\tip_keyevent_handler.cc'
$needle = @'
  // TSF spec guarantees that key event handling can always be a synchronous
  // operation.
  TipEditSession::OnOutputReceivedSync(text_service, context, temporal_output);
'@
$replacement = @'
  // Preserve the server output before the experimental responsibility layer
  // starts rewriting ownership. This snapshot is behavior-neutral for now.
  *private_context->mutable_responsibility_base_output() = temporal_output;

  // TSF spec guarantees that key event handling can always be a synchronous
  // operation.
  TipEditSession::OnOutputReceivedSync(text_service, context, temporal_output);
'@
Replace-Once -Path $keyHandler -Needle $needle -Replacement $replacement -AlreadyPresent 'mutable_responsibility_base_output() = temporal_output'

if (-not $VcPath) {
    $programFilesX86 = [Environment]::GetEnvironmentVariable('ProgramFiles(x86)')
    $vswhere = Join-Path $programFilesX86 'Microsoft Visual Studio\Installer\vswhere.exe'
    $vs = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    if (-not $vs) { throw 'Visual Studio C++ workload was not found.' }
    $VcPath = Join-Path $vs 'VC'
}

Push-Location $src
try {
    Invoke-Native $Python @('build_tools/update_deps.py', '--noqt', '--nowix', '--nondk') 'Mozc dependency update failed'
    $env:BAZEL_VC = $VcPath
    $prefix = @('--nowindows_enable_symlinks')
    $cache = @()
    if ($DiskCache) { $cache += "--disk_cache=$DiskCache" }

    if (-not $SkipTests) {
        Invoke-Native $Bazelisk ($prefix + @(
            'test',
            '//win32/tip/meltype:responsibility_decoder_test',
            '//win32/tip/meltype:responsibility_runtime_test',
            '--config', 'release_build'
        ) + $cache) 'responsibility unit tests failed'
    }

    Invoke-Native $Bazelisk ($prefix + @(
        'build',
        '//win32/tip/meltype:boundary_mozc_bridge',
        '--config', 'release_build'
    ) + $cache) 'boundary_mozc_bridge build failed'

    if (-not $SkipTipBuild) {
        Invoke-Native $Bazelisk ($prefix + @(
            'build',
            '//win32/tip:mozc_tip64',
            '--config', 'release_build'
        ) + $cache) 'mozc_tip64 build failed'
    }
} finally {
    Pop-Location
}

$bin = Join-Path $experimental 'bin'
New-Item -ItemType Directory -Force -Path $bin | Out-Null
$bridgeOutput = Get-ChildItem -Path (Join-Path $src 'bazel-bin\win32\tip\meltype') -Recurse -Filter 'boundary_mozc_bridge.exe' -File | Select-Object -First 1 -ExpandProperty FullName
if (-not $bridgeOutput) { throw 'boundary_mozc_bridge output was not found.' }
Copy-Item -LiteralPath $bridgeOutput -Destination (Join-Path $bin 'boundary_mozc_bridge.exe') -Force

if (-not $SkipTipBuild) {
    $tip = Get-ChildItem -Path (Join-Path $src 'bazel-bin\win32\tip') -Recurse -Filter 'mozc_tip64.dll' -File | Select-Object -First 1 -ExpandProperty FullName
    if (-not $tip) { throw 'mozc_tip64.dll output was not found.' }
    Copy-Item -LiteralPath $tip -Destination (Join-Path $bin 'mozc_tip64.dll') -Force
}

Write-Host ''
Write-Host 'Responsibility IME experiment build succeeded.'
Write-Host ('  bridge: ' + (Join-Path $bin 'boundary_mozc_bridge.exe'))
if (-not $SkipTipBuild) {
    Write-Host ('  TIP:    ' + (Join-Path $bin 'mozc_tip64.dll'))
}
